version: '3.11'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis
    ports:
      - 6379:6379

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis

  celery:
    build:
      context: .
    command: celery -A CargoService worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  celery-beat:
    build:
      context: .
    command: celery -A CargoService beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
